CREATE TABLE "earnings_analyses" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"symbol" text NOT NULL,
	"period" text NOT NULL,
	"locale" text DEFAULT 'tr' NOT NULL,
	"period_label" text NOT NULL,
	"company" text NOT NULL,
	"exchange" text,
	"sector" text,
	"report_date" date NOT NULL,
	"timing" text,
	"next_period_label" text,
	"next_report_estimate" text,
	"score" integer NOT NULL,
	"verdict" text NOT NULL,
	"headline" text NOT NULL,
	"price" double precision,
	"reaction_pct" double precision,
	"market_cap" double precision,
	"return_1y_pct" double precision,
	"target_price" double precision,
	"upside_pct" double precision,
	"analyst_count" integer,
	"revenue" double precision,
	"revenue_yoy_pct" double precision,
	"eps" double precision,
	"eps_surprise_pct" double precision,
	"summary" jsonb NOT NULL,
	"analysis" jsonb NOT NULL,
	"strengths" jsonb,
	"risks" jsonb,
	"upcoming" jsonb,
	"highlights" jsonb,
	"ceo_quote" jsonb,
	"sources" jsonb,
	"card_image_url" text,
	"generated_by" text DEFAULT 'claude' NOT NULL,
	"published_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX "earnings_analyses_key" ON "earnings_analyses" USING btree ("symbol","period","locale");--> statement-breakpoint
CREATE INDEX "earnings_analyses_report_idx" ON "earnings_analyses" USING btree ("report_date");--> statement-breakpoint
CREATE INDEX "earnings_analyses_symbol_idx" ON "earnings_analyses" USING btree ("symbol");