/**
 * Endeks bileşen listeleri — Piyasalar sayfasının ve sektör önerilerinin tabanı.
 *
 * Kaynak: Wikipedia bileşen tabloları (List of S&P 500 companies,
 * Dow Jones Industrial Average, Nasdaq-100), 1 Ağustos 2026'da çekildi.
 * `sector`/`sub` alanları GICS sınıflandırmasıdır; S&P 500 tablosundan gelir,
 * yalnızca o endekste bulunmayan üyeler için elle tamamlanmıştır.
 *
 * Endeks kompozisyonları yılda birkaç kez değişir; tazelemek için bu dosya
 * aynı kaynaktan yeniden üretilir. Fiyat/piyasa değeri BURADAN GELMEZ —
 * yalnızca üyelik, ad ve sektör statiktir; sayısal veri canlı sağlayıcıdan gelir.
 */

export type IndexMember = {
  symbol: string;
  name: string;
  /** GICS sektörü — geniş sınıflandırma. */
  sector?: string;
  /** GICS alt sektörü — "Semiconductors" gibi; benzer hisse önerisi buna bakar. */
  sub?: string;
};

export const INDEX_COMPOSITION_DATE = "2026-08-01";

/** Dow Jones Industrial Average — 30 üye. */
export const DOW_MEMBERS: IndexMember[] = [
  { symbol: "AAPL", name: "Apple", sector: "Information Technology", sub: "Technology Hardware, Storage & Peripherals" },
  { symbol: "AMGN", name: "Amgen", sector: "Health Care", sub: "Biotechnology" },
  { symbol: "AMZN", name: "Amazon", sector: "Consumer Discretionary", sub: "Broadline Retail" },
  { symbol: "AXP", name: "American Express", sector: "Financials", sub: "Consumer Finance" },
  { symbol: "BA", name: "Boeing", sector: "Industrials", sub: "Aerospace & Defense" },
  { symbol: "CAT", name: "Caterpillar", sector: "Industrials", sub: "Construction Machinery & Heavy Transportation Equipment" },
  { symbol: "CRM", name: "Salesforce", sector: "Information Technology", sub: "Application Software" },
  { symbol: "CSCO", name: "Cisco", sector: "Information Technology", sub: "Communications Equipment" },
  { symbol: "CVX", name: "Chevron", sector: "Energy", sub: "Integrated Oil & Gas" },
  { symbol: "DIS", name: "Disney", sector: "Communication Services", sub: "Movies & Entertainment" },
  { symbol: "GOOGL", name: "Alphabet", sector: "Communication Services", sub: "Interactive Media & Services" },
  { symbol: "GS", name: "Goldman Sachs", sector: "Financials", sub: "Investment Banking & Brokerage" },
  { symbol: "HD", name: "Home Depot", sector: "Consumer Discretionary", sub: "Home Improvement Retail" },
  { symbol: "HON", name: "Honeywell Technologies", sector: "Industrials", sub: "Industrial Conglomerates" },
  { symbol: "IBM", name: "IBM", sector: "Information Technology", sub: "IT Consulting & Other Services" },
  { symbol: "JNJ", name: "Johnson & Johnson", sector: "Health Care", sub: "Pharmaceuticals" },
  { symbol: "JPM", name: "JPMorgan Chase", sector: "Financials", sub: "Diversified Banks" },
  { symbol: "KO", name: "Coca-Cola", sector: "Consumer Staples", sub: "Soft Drinks & Non-alcoholic Beverages" },
  { symbol: "MCD", name: "McDonald's", sector: "Consumer Discretionary", sub: "Restaurants" },
  { symbol: "MMM", name: "3M", sector: "Industrials", sub: "Industrial Conglomerates" },
  { symbol: "MRK", name: "Merck", sector: "Health Care", sub: "Pharmaceuticals" },
  { symbol: "MSFT", name: "Microsoft", sector: "Information Technology", sub: "Systems Software" },
  { symbol: "NKE", name: "Nike", sector: "Consumer Discretionary", sub: "Apparel, Accessories & Luxury Goods" },
  { symbol: "NVDA", name: "Nvidia", sector: "Information Technology", sub: "Semiconductors" },
  { symbol: "PG", name: "Procter & Gamble", sector: "Consumer Staples", sub: "Personal Care Products" },
  { symbol: "SHW", name: "Sherwin-Williams", sector: "Materials", sub: "Specialty Chemicals" },
  { symbol: "TRV", name: "Travelers", sector: "Financials", sub: "Property & Casualty Insurance" },
  { symbol: "UNH", name: "UnitedHealth Group", sector: "Health Care", sub: "Managed Health Care" },
  { symbol: "V", name: "Visa", sector: "Financials", sub: "Transaction & Payment Processing Services" },
  { symbol: "WMT", name: "Walmart", sector: "Consumer Staples", sub: "Consumer Staples Merchandise Retail" },
];

/** Nasdaq-100 — 100 üye. */
export const NDX_MEMBERS: IndexMember[] = [
  { symbol: "AAPL", name: "Apple Inc.", sector: "Information Technology", sub: "Technology Hardware, Storage & Peripherals" },
  { symbol: "ABNB", name: "Airbnb", sector: "Consumer Discretionary", sub: "Hotels, Resorts & Cruise Lines" },
  { symbol: "ADBE", name: "Adobe Inc.", sector: "Information Technology", sub: "Application Software" },
  { symbol: "ADI", name: "Analog Devices", sector: "Information Technology", sub: "Semiconductors" },
  { symbol: "ADP", name: "ADP", sector: "Industrials", sub: "Human Resource & Employment Services" },
  { symbol: "ADSK", name: "Autodesk", sector: "Information Technology", sub: "Application Software" },
  { symbol: "AEP", name: "American Electric Power", sector: "Utilities", sub: "Electric Utilities" },
  { symbol: "ALAB", name: "Astera Labs", sector: "Information Technology", sub: "Semiconductors" },
  { symbol: "ALNY", name: "Alnylam Pharmaceuticals", sector: "Health Care", sub: "Biotechnology" },
  { symbol: "AMAT", name: "Applied Materials", sector: "Information Technology", sub: "Semiconductor Materials & Equipment" },
  { symbol: "AMD", name: "AMD", sector: "Information Technology", sub: "Semiconductors" },
  { symbol: "AMGN", name: "Amgen", sector: "Health Care", sub: "Biotechnology" },
  { symbol: "AMZN", name: "Amazon", sector: "Consumer Discretionary", sub: "Broadline Retail" },
  { symbol: "APP", name: "AppLovin", sector: "Information Technology", sub: "Application Software" },
  { symbol: "ARM", name: "Arm Holdings", sector: "Information Technology", sub: "Semiconductors" },
  { symbol: "ASML", name: "ASML Holding", sector: "Information Technology", sub: "Semiconductor Materials & Equipment" },
  { symbol: "AVGO", name: "Broadcom", sector: "Information Technology", sub: "Semiconductors" },
  { symbol: "AXON", name: "Axon Enterprise", sector: "Industrials", sub: "Aerospace & Defense" },
  { symbol: "BKNG", name: "Booking Holdings", sector: "Consumer Discretionary", sub: "Hotels, Resorts & Cruise Lines" },
  { symbol: "BKR", name: "Baker Hughes", sector: "Energy", sub: "Oil & Gas Equipment & Services" },
  { symbol: "CCEP", name: "Coca-Cola Europacific Partners", sector: "Consumer Staples", sub: "Soft Drinks & Non-alcoholic Beverages" },
  { symbol: "CDNS", name: "Cadence Design Systems", sector: "Information Technology", sub: "Application Software" },
  { symbol: "CEG", name: "Constellation Energy", sector: "Utilities", sub: "Electric Utilities" },
  { symbol: "CMCSA", name: "Comcast", sector: "Communication Services", sub: "Cable & Satellite" },
  { symbol: "COST", name: "Costco", sector: "Consumer Staples", sub: "Consumer Staples Merchandise Retail" },
  { symbol: "CPRT", name: "Copart", sector: "Industrials", sub: "Diversified Support Services" },
  { symbol: "CRWD", name: "CrowdStrike", sector: "Information Technology", sub: "Systems Software" },
  { symbol: "CRWV", name: "CoreWeave", sector: "Information Technology", sub: "Internet Services & Infrastructure" },
  { symbol: "CSCO", name: "Cisco", sector: "Information Technology", sub: "Communications Equipment" },
  { symbol: "CSX", name: "CSX Corporation", sector: "Industrials", sub: "Rail Transportation" },
  { symbol: "CTAS", name: "Cintas", sector: "Industrials", sub: "Diversified Support Services" },
  { symbol: "DASH", name: "DoorDash", sector: "Consumer Discretionary", sub: "Specialized Consumer Services" },
  { symbol: "DDOG", name: "Datadog", sector: "Information Technology", sub: "Application Software" },
  { symbol: "DXCM", name: "Dexcom", sector: "Health Care", sub: "Health Care Equipment" },
  { symbol: "EA", name: "Electronic Arts", sector: "Communication Services", sub: "Interactive Home Entertainment" },
  { symbol: "EXC", name: "Exelon", sector: "Utilities", sub: "Electric Utilities" },
  { symbol: "FANG", name: "Diamondback Energy", sector: "Energy", sub: "Oil & Gas Exploration & Production" },
  { symbol: "FAST", name: "Fastenal", sector: "Industrials", sub: "Trading Companies & Distributors" },
  { symbol: "FER", name: "Ferrovial", sector: "Industrials", sub: "Construction & Engineering" },
  { symbol: "FTNT", name: "Fortinet", sector: "Information Technology", sub: "Systems Software" },
  { symbol: "GEHC", name: "GE HealthCare", sector: "Health Care", sub: "Health Care Equipment" },
  { symbol: "GILD", name: "Gilead Sciences", sector: "Health Care", sub: "Biotechnology" },
  { symbol: "GOOGL", name: "Alphabet Inc.", sector: "Communication Services", sub: "Interactive Media & Services" },
  { symbol: "HON", name: "Honeywell", sector: "Industrials", sub: "Industrial Conglomerates" },
  { symbol: "IDXX", name: "Idexx Laboratories", sector: "Health Care", sub: "Health Care Equipment" },
  { symbol: "INTC", name: "Intel", sector: "Information Technology", sub: "Semiconductors" },
  { symbol: "INTU", name: "Intuit", sector: "Information Technology", sub: "Application Software" },
  { symbol: "ISRG", name: "Intuitive Surgical", sector: "Health Care", sub: "Health Care Equipment" },
  { symbol: "KDP", name: "Keurig Dr Pepper", sector: "Consumer Staples", sub: "Soft Drinks & Non-alcoholic Beverages" },
  { symbol: "KHC", name: "Kraft Heinz", sector: "Consumer Staples", sub: "Packaged Foods & Meats" },
  { symbol: "KLAC", name: "KLA", sector: "Information Technology", sub: "Semiconductor Materials & Equipment" },
  { symbol: "LIN", name: "Linde", sector: "Materials", sub: "Industrial Gases" },
  { symbol: "LITE", name: "Lumentum", sector: "Information Technology", sub: "Communications Equipment" },
  { symbol: "LRCX", name: "Lam Research", sector: "Information Technology", sub: "Semiconductor Materials & Equipment" },
  { symbol: "MAR", name: "Marriott International", sector: "Consumer Discretionary", sub: "Hotels, Resorts & Cruise Lines" },
  { symbol: "MCHP", name: "Microchip Technology", sector: "Information Technology", sub: "Semiconductors" },
  { symbol: "MDLZ", name: "Mondelez International", sector: "Consumer Staples", sub: "Packaged Foods & Meats" },
  { symbol: "MELI", name: "MercadoLibre", sector: "Consumer Discretionary", sub: "Broadline Retail" },
  { symbol: "META", name: "Meta Platforms", sector: "Communication Services", sub: "Interactive Media & Services" },
  { symbol: "MNST", name: "Monster Beverage", sector: "Consumer Staples", sub: "Soft Drinks & Non-alcoholic Beverages" },
  { symbol: "MPWR", name: "Monolithic Power Systems", sector: "Information Technology", sub: "Semiconductors" },
  { symbol: "MRVL", name: "Marvell Technology", sector: "Information Technology", sub: "Semiconductors" },
  { symbol: "MSFT", name: "Microsoft", sector: "Information Technology", sub: "Systems Software" },
  { symbol: "MSTR", name: "Strategy (MicroStrategy)", sector: "Information Technology", sub: "Application Software" },
  { symbol: "MU", name: "Micron Technology", sector: "Information Technology", sub: "Semiconductors" },
  { symbol: "NBIS", name: "Nebius Group", sector: "Information Technology", sub: "Internet Services & Infrastructure" },
  { symbol: "NFLX", name: "Netflix", sector: "Communication Services", sub: "Movies & Entertainment" },
  { symbol: "NVDA", name: "NVIDIA", sector: "Information Technology", sub: "Semiconductors" },
  { symbol: "NXPI", name: "NXP Semiconductors", sector: "Information Technology", sub: "Semiconductors" },
  { symbol: "ODFL", name: "Old Dominion Freight Line", sector: "Industrials", sub: "Cargo Ground Transportation" },
  { symbol: "ORLY", name: "O'Reilly Auto Parts", sector: "Consumer Discretionary", sub: "Automotive Retail" },
  { symbol: "PANW", name: "Palo Alto Networks", sector: "Information Technology", sub: "Systems Software" },
  { symbol: "PAYX", name: "Paychex", sector: "Industrials", sub: "Human Resource & Employment Services" },
  { symbol: "PCAR", name: "PACCAR", sector: "Industrials", sub: "Construction Machinery & Heavy Transportation Equipment" },
  { symbol: "PDD", name: "PDD Holdings", sector: "Consumer Discretionary", sub: "Broadline Retail" },
  { symbol: "PEP", name: "PepsiCo", sector: "Consumer Staples", sub: "Soft Drinks & Non-alcoholic Beverages" },
  { symbol: "PLTR", name: "Palantir", sector: "Information Technology", sub: "Application Software" },
  { symbol: "PYPL", name: "PayPal", sector: "Financials", sub: "Transaction & Payment Processing Services" },
  { symbol: "QCOM", name: "Qualcomm", sector: "Information Technology", sub: "Semiconductors" },
  { symbol: "REGN", name: "Regeneron Pharmaceuticals", sector: "Health Care", sub: "Biotechnology" },
  { symbol: "RKLB", name: "Rocket Lab", sector: "Industrials", sub: "Aerospace & Defense" },
  { symbol: "ROP", name: "Roper Technologies", sector: "Information Technology", sub: "Electronic Equipment & Instruments" },
  { symbol: "ROST", name: "Ross Stores", sector: "Consumer Discretionary", sub: "Apparel Retail" },
  { symbol: "SBUX", name: "Starbucks", sector: "Consumer Discretionary", sub: "Restaurants" },
  { symbol: "SHOP", name: "Shopify", sector: "Information Technology", sub: "Application Software" },
  { symbol: "SNDK", name: "SanDisk", sector: "Information Technology", sub: "Technology Hardware, Storage & Peripherals" },
  { symbol: "SNPS", name: "Synopsys", sector: "Information Technology", sub: "Application Software" },
  { symbol: "STX", name: "Seagate Technology", sector: "Information Technology", sub: "Technology Hardware, Storage & Peripherals" },
  { symbol: "TER", name: "Teradyne", sector: "Information Technology", sub: "Semiconductor Materials & Equipment" },
  { symbol: "TMUS", name: "T-Mobile US", sector: "Communication Services", sub: "Wireless Telecommunication Services" },
  { symbol: "TRI", name: "Thomson Reuters", sector: "Industrials", sub: "Research & Consulting Services" },
  { symbol: "TSLA", name: "Tesla", sector: "Consumer Discretionary", sub: "Automobile Manufacturers" },
  { symbol: "TTWO", name: "Take-Two Interactive", sector: "Communication Services", sub: "Interactive Home Entertainment" },
  { symbol: "TXN", name: "Texas Instruments", sector: "Information Technology", sub: "Semiconductors" },
  { symbol: "VRTX", name: "Vertex Pharmaceuticals", sector: "Health Care", sub: "Biotechnology" },
  { symbol: "WBD", name: "Warner Bros. Discovery", sector: "Communication Services", sub: "Broadcasting" },
  { symbol: "WDAY", name: "Workday", sector: "Information Technology", sub: "Application Software" },
  { symbol: "WDC", name: "Western Digital", sector: "Information Technology", sub: "Technology Hardware, Storage & Peripherals" },
  { symbol: "WMT", name: "Walmart", sector: "Consumer Staples", sub: "Consumer Staples Merchandise Retail" },
  { symbol: "XEL", name: "Xcel Energy", sector: "Utilities", sub: "Multi-Utilities" },
];

/** S&P 500 — 502 üye. */
export const SPX_MEMBERS: IndexMember[] = [
  { symbol: "A", name: "Agilent Technologies", sector: "Health Care", sub: "Life Sciences Tools & Services" },
  { symbol: "AAPL", name: "Apple Inc.", sector: "Information Technology", sub: "Technology Hardware, Storage & Peripherals" },
  { symbol: "ABBV", name: "AbbVie", sector: "Health Care", sub: "Biotechnology" },
  { symbol: "ABNB", name: "Airbnb", sector: "Consumer Discretionary", sub: "Hotels, Resorts & Cruise Lines" },
  { symbol: "ABT", name: "Abbott Laboratories", sector: "Health Care", sub: "Health Care Equipment" },
  { symbol: "ACGL", name: "Arch Capital Group", sector: "Financials", sub: "Property & Casualty Insurance" },
  { symbol: "ACN", name: "Accenture", sector: "Information Technology", sub: "IT Consulting & Other Services" },
  { symbol: "ADBE", name: "Adobe Inc.", sector: "Information Technology", sub: "Application Software" },
  { symbol: "ADI", name: "Analog Devices", sector: "Information Technology", sub: "Semiconductors" },
  { symbol: "ADM", name: "Archer Daniels Midland", sector: "Consumer Staples", sub: "Agricultural Products & Services" },
  { symbol: "ADP", name: "Automatic Data Processing", sector: "Industrials", sub: "Human Resource & Employment Services" },
  { symbol: "ADSK", name: "Autodesk", sector: "Information Technology", sub: "Application Software" },
  { symbol: "AEE", name: "Ameren", sector: "Utilities", sub: "Multi-Utilities" },
  { symbol: "AEP", name: "American Electric Power", sector: "Utilities", sub: "Electric Utilities" },
  { symbol: "AES", name: "AES Corporation", sector: "Utilities", sub: "Independent Power Producers & Energy Traders" },
  { symbol: "AFL", name: "Aflac", sector: "Financials", sub: "Life & Health Insurance" },
  { symbol: "AIG", name: "American International Group", sector: "Financials", sub: "Multi-line Insurance" },
  { symbol: "AIZ", name: "Assurant", sector: "Financials", sub: "Multi-line Insurance" },
  { symbol: "AJG", name: "Arthur J. Gallagher & Co.", sector: "Financials", sub: "Insurance Brokers" },
  { symbol: "AKAM", name: "Akamai Technologies", sector: "Information Technology", sub: "Internet Services & Infrastructure" },
  { symbol: "ALB", name: "Albemarle Corporation", sector: "Materials", sub: "Specialty Chemicals" },
  { symbol: "ALGN", name: "Align Technology", sector: "Health Care", sub: "Health Care Supplies" },
  { symbol: "ALL", name: "Allstate", sector: "Financials", sub: "Property & Casualty Insurance" },
  { symbol: "ALLE", name: "Allegion", sector: "Industrials", sub: "Building Products" },
  { symbol: "AMAT", name: "Applied Materials", sector: "Information Technology", sub: "Semiconductor Materials & Equipment" },
  { symbol: "AMCR", name: "Amcor", sector: "Materials", sub: "Paper & Plastic Packaging Products & Materials" },
  { symbol: "AMD", name: "Advanced Micro Devices", sector: "Information Technology", sub: "Semiconductors" },
  { symbol: "AME", name: "Ametek", sector: "Industrials", sub: "Electrical Components & Equipment" },
  { symbol: "AMGN", name: "Amgen", sector: "Health Care", sub: "Biotechnology" },
  { symbol: "AMP", name: "Ameriprise Financial", sector: "Financials", sub: "Asset Management & Custody Banks" },
  { symbol: "AMT", name: "American Tower", sector: "Real Estate", sub: "Telecom Tower REITs" },
  { symbol: "AMZN", name: "Amazon", sector: "Consumer Discretionary", sub: "Broadline Retail" },
  { symbol: "ANET", name: "Arista Networks", sector: "Information Technology", sub: "Communications Equipment" },
  { symbol: "AON", name: "Aon plc", sector: "Financials", sub: "Insurance Brokers" },
  { symbol: "AOS", name: "A. O. Smith", sector: "Industrials", sub: "Building Products" },
  { symbol: "APA", name: "APA Corporation", sector: "Energy", sub: "Oil & Gas Exploration & Production" },
  { symbol: "APD", name: "Air Products", sector: "Materials", sub: "Industrial Gases" },
  { symbol: "APH", name: "Amphenol", sector: "Information Technology", sub: "Electronic Components" },
  { symbol: "APO", name: "Apollo Global Management", sector: "Financials", sub: "Asset Management & Custody Banks" },
  { symbol: "APP", name: "AppLovin", sector: "Information Technology", sub: "Application Software" },
  { symbol: "APTV", name: "Aptiv", sector: "Consumer Discretionary", sub: "Automotive Parts & Equipment" },
  { symbol: "ARE", name: "Alexandria Real Estate Equities", sector: "Real Estate", sub: "Office REITs" },
  { symbol: "ARES", name: "Ares Management", sector: "Financials", sub: "Asset Management & Custody Banks" },
  { symbol: "ATO", name: "Atmos Energy", sector: "Utilities", sub: "Gas Utilities" },
  { symbol: "AVB", name: "AvalonBay Communities", sector: "Real Estate", sub: "Multi-Family Residential REITs" },
  { symbol: "AVGO", name: "Broadcom", sector: "Information Technology", sub: "Semiconductors" },
  { symbol: "AVY", name: "Avery Dennison", sector: "Materials", sub: "Paper & Plastic Packaging Products & Materials" },
  { symbol: "AWK", name: "American Water Works", sector: "Utilities", sub: "Water Utilities" },
  { symbol: "AXON", name: "Axon Enterprise", sector: "Industrials", sub: "Aerospace & Defense" },
  { symbol: "AXP", name: "American Express", sector: "Financials", sub: "Consumer Finance" },
  { symbol: "AZO", name: "AutoZone", sector: "Consumer Discretionary", sub: "Automotive Retail" },
  { symbol: "BA", name: "Boeing", sector: "Industrials", sub: "Aerospace & Defense" },
  { symbol: "BAC", name: "Bank of America", sector: "Financials", sub: "Diversified Banks" },
  { symbol: "BALL", name: "Ball Corporation", sector: "Materials", sub: "Metal, Glass & Plastic Containers" },
  { symbol: "BAX", name: "Baxter International", sector: "Health Care", sub: "Health Care Equipment" },
  { symbol: "BBY", name: "Best Buy", sector: "Consumer Discretionary", sub: "Computer & Electronics Retail" },
  { symbol: "BDX", name: "Becton Dickinson", sector: "Health Care", sub: "Health Care Equipment" },
  { symbol: "BEN", name: "Franklin Resources", sector: "Financials", sub: "Asset Management & Custody Banks" },
  { symbol: "BF.B", name: "Brown–Forman", sector: "Consumer Staples", sub: "Distillers & Vintners" },
  { symbol: "BG", name: "Bunge Global", sector: "Consumer Staples", sub: "Agricultural Products & Services" },
  { symbol: "BIIB", name: "Biogen", sector: "Health Care", sub: "Biotechnology" },
  { symbol: "BKNG", name: "Booking Holdings", sector: "Consumer Discretionary", sub: "Hotels, Resorts & Cruise Lines" },
  { symbol: "BKR", name: "Baker Hughes", sector: "Energy", sub: "Oil & Gas Equipment & Services" },
  { symbol: "BLDR", name: "Builders FirstSource", sector: "Industrials", sub: "Building Products" },
  { symbol: "BLK", name: "BlackRock", sector: "Financials", sub: "Asset Management & Custody Banks" },
  { symbol: "BMY", name: "Bristol Myers Squibb", sector: "Health Care", sub: "Pharmaceuticals" },
  { symbol: "BNY", name: "BNY Mellon", sector: "Financials", sub: "Asset Management & Custody Banks" },
  { symbol: "BR", name: "Broadridge Financial Solutions", sector: "Industrials", sub: "Data Processing & Outsourced Services" },
  { symbol: "BRK.B", name: "Berkshire Hathaway", sector: "Financials", sub: "Multi-Sector Holdings" },
  { symbol: "BRO", name: "Brown & Brown", sector: "Financials", sub: "Insurance Brokers" },
  { symbol: "BSX", name: "Boston Scientific", sector: "Health Care", sub: "Health Care Equipment" },
  { symbol: "BX", name: "Blackstone Inc.", sector: "Financials", sub: "Asset Management & Custody Banks" },
  { symbol: "BXP", name: "BXP, Inc.", sector: "Real Estate", sub: "Office REITs" },
  { symbol: "C", name: "Citigroup", sector: "Financials", sub: "Diversified Banks" },
  { symbol: "CAH", name: "Cardinal Health", sector: "Health Care", sub: "Health Care Distributors" },
  { symbol: "CARR", name: "Carrier Global", sector: "Industrials", sub: "Building Products" },
  { symbol: "CASY", name: "Casey's", sector: "Consumer Staples", sub: "Food Retail" },
  { symbol: "CAT", name: "Caterpillar Inc.", sector: "Industrials", sub: "Construction Machinery & Heavy Transportation Equipment" },
  { symbol: "CB", name: "Chubb Limited", sector: "Financials", sub: "Property & Casualty Insurance" },
  { symbol: "CBOE", name: "Cboe Global Markets", sector: "Financials", sub: "Financial Exchanges & Data" },
  { symbol: "CBRE", name: "CBRE Group", sector: "Real Estate", sub: "Real Estate Services" },
  { symbol: "CCI", name: "Crown Castle", sector: "Real Estate", sub: "Telecom Tower REITs" },
  { symbol: "CCL", name: "Carnival Corporation", sector: "Consumer Discretionary", sub: "Hotels, Resorts & Cruise Lines" },
  { symbol: "CDNS", name: "Cadence Design Systems", sector: "Information Technology", sub: "Application Software" },
  { symbol: "CDW", name: "CDW Corporation", sector: "Information Technology", sub: "Technology Distributors" },
  { symbol: "CEG", name: "Constellation Energy", sector: "Utilities", sub: "Electric Utilities" },
  { symbol: "CF", name: "CF Industries", sector: "Materials", sub: "Fertilizers & Agricultural Chemicals" },
  { symbol: "CFG", name: "Citizens Financial Group", sector: "Financials", sub: "Regional Banks" },
  { symbol: "CHD", name: "Church & Dwight", sector: "Consumer Staples", sub: "Household Products" },
  { symbol: "CHRW", name: "C.H. Robinson", sector: "Industrials", sub: "Air Freight & Logistics" },
  { symbol: "CHTR", name: "Charter Communications", sector: "Communication Services", sub: "Cable & Satellite" },
  { symbol: "CI", name: "Cigna", sector: "Health Care", sub: "Health Care Services" },
  { symbol: "CIEN", name: "Ciena", sector: "Information Technology", sub: "Communications Equipment" },
  { symbol: "CINF", name: "Cincinnati Financial", sector: "Financials", sub: "Property & Casualty Insurance" },
  { symbol: "CL", name: "Colgate-Palmolive", sector: "Consumer Staples", sub: "Household Products" },
  { symbol: "CLX", name: "Clorox", sector: "Consumer Staples", sub: "Household Products" },
  { symbol: "CMCSA", name: "Comcast", sector: "Communication Services", sub: "Cable & Satellite" },
  { symbol: "CME", name: "CME Group", sector: "Financials", sub: "Financial Exchanges & Data" },
  { symbol: "CMG", name: "Chipotle Mexican Grill", sector: "Consumer Discretionary", sub: "Restaurants" },
  { symbol: "CMI", name: "Cummins", sector: "Industrials", sub: "Construction Machinery & Heavy Transportation Equipment" },
  { symbol: "CMS", name: "CMS Energy", sector: "Utilities", sub: "Multi-Utilities" },
  { symbol: "CNC", name: "Centene Corporation", sector: "Health Care", sub: "Managed Health Care" },
  { symbol: "CNP", name: "CenterPoint Energy", sector: "Utilities", sub: "Multi-Utilities" },
  { symbol: "COF", name: "Capital One", sector: "Financials", sub: "Consumer Finance" },
  { symbol: "COHR", name: "Coherent Corp.", sector: "Information Technology", sub: "Electronic Components" },
  { symbol: "COIN", name: "Coinbase", sector: "Financials", sub: "Financial Exchanges & Data" },
  { symbol: "COO", name: "Cooper Companies (The)", sector: "Health Care", sub: "Health Care Supplies" },
  { symbol: "COP", name: "ConocoPhillips", sector: "Energy", sub: "Oil & Gas Exploration & Production" },
  { symbol: "COR", name: "Cencora", sector: "Health Care", sub: "Health Care Distributors" },
  { symbol: "COST", name: "Costco", sector: "Consumer Staples", sub: "Consumer Staples Merchandise Retail" },
  { symbol: "CPAY", name: "Corpay", sector: "Financials", sub: "Transaction & Payment Processing Services" },
  { symbol: "CPRT", name: "Copart", sector: "Industrials", sub: "Diversified Support Services" },
  { symbol: "CPT", name: "Camden Property Trust", sector: "Real Estate", sub: "Multi-Family Residential REITs" },
  { symbol: "CRH", name: "CRH plc", sector: "Materials", sub: "Construction Materials" },
  { symbol: "CRL", name: "Charles River Laboratories", sector: "Health Care", sub: "Life Sciences Tools & Services" },
  { symbol: "CRM", name: "Salesforce", sector: "Information Technology", sub: "Application Software" },
  { symbol: "CRWD", name: "CrowdStrike", sector: "Information Technology", sub: "Systems Software" },
  { symbol: "CSCO", name: "Cisco", sector: "Information Technology", sub: "Communications Equipment" },
  { symbol: "CSGP", name: "CoStar Group", sector: "Real Estate", sub: "Real Estate Services" },
  { symbol: "CSX", name: "CSX Corporation", sector: "Industrials", sub: "Rail Transportation" },
  { symbol: "CTAS", name: "Cintas", sector: "Industrials", sub: "Diversified Support Services" },
  { symbol: "CTSH", name: "Cognizant", sector: "Information Technology", sub: "IT Consulting & Other Services" },
  { symbol: "CTVA", name: "Corteva", sector: "Materials", sub: "Fertilizers & Agricultural Chemicals" },
  { symbol: "CVNA", name: "Carvana", sector: "Consumer Discretionary", sub: "Automotive Retail" },
  { symbol: "CVS", name: "CVS Health", sector: "Health Care", sub: "Health Care Services" },
  { symbol: "CVX", name: "Chevron Corporation", sector: "Energy", sub: "Integrated Oil & Gas" },
  { symbol: "D", name: "Dominion Energy", sector: "Utilities", sub: "Multi-Utilities" },
  { symbol: "DAL", name: "Delta Air Lines", sector: "Industrials", sub: "Passenger Airlines" },
  { symbol: "DASH", name: "DoorDash", sector: "Consumer Discretionary", sub: "Specialized Consumer Services" },
  { symbol: "DD", name: "DuPont", sector: "Materials", sub: "Specialty Chemicals" },
  { symbol: "DDOG", name: "Datadog", sector: "Information Technology", sub: "Application Software" },
  { symbol: "DE", name: "Deere & Company", sector: "Industrials", sub: "Agricultural & Farm Machinery" },
  { symbol: "DECK", name: "Deckers Brands", sector: "Consumer Discretionary", sub: "Footwear" },
  { symbol: "DELL", name: "Dell Technologies", sector: "Information Technology", sub: "Technology Hardware, Storage & Peripherals" },
  { symbol: "DG", name: "Dollar General", sector: "Consumer Staples", sub: "Consumer Staples Merchandise Retail" },
  { symbol: "DGX", name: "Quest Diagnostics", sector: "Health Care", sub: "Health Care Services" },
  { symbol: "DHI", name: "D. R. Horton", sector: "Consumer Discretionary", sub: "Homebuilding" },
  { symbol: "DHR", name: "Danaher Corporation", sector: "Health Care", sub: "Life Sciences Tools & Services" },
  { symbol: "DIS", name: "Walt Disney Company (The)", sector: "Communication Services", sub: "Movies & Entertainment" },
  { symbol: "DLR", name: "Digital Realty", sector: "Real Estate", sub: "Data Center REITs" },
  { symbol: "DLTR", name: "Dollar Tree", sector: "Consumer Staples", sub: "Consumer Staples Merchandise Retail" },
  { symbol: "DOC", name: "Healthpeak Properties", sector: "Real Estate", sub: "Health Care REITs" },
  { symbol: "DOV", name: "Dover Corporation", sector: "Industrials", sub: "Industrial Machinery & Supplies & Components" },
  { symbol: "DOW", name: "Dow Inc.", sector: "Materials", sub: "Commodity Chemicals" },
  { symbol: "DPZ", name: "Domino's", sector: "Consumer Discretionary", sub: "Restaurants" },
  { symbol: "DRI", name: "Darden Restaurants", sector: "Consumer Discretionary", sub: "Restaurants" },
  { symbol: "DTE", name: "DTE Energy", sector: "Utilities", sub: "Multi-Utilities" },
  { symbol: "DUK", name: "Duke Energy", sector: "Utilities", sub: "Electric Utilities" },
  { symbol: "DVA", name: "DaVita", sector: "Health Care", sub: "Health Care Services" },
  { symbol: "DVN", name: "Devon Energy", sector: "Energy", sub: "Oil & Gas Exploration & Production" },
  { symbol: "DXCM", name: "Dexcom", sector: "Health Care", sub: "Health Care Equipment" },
  { symbol: "EA", name: "Electronic Arts", sector: "Communication Services", sub: "Interactive Home Entertainment" },
  { symbol: "EBAY", name: "eBay Inc.", sector: "Consumer Discretionary", sub: "Broadline Retail" },
  { symbol: "ECHO", name: "EchoStar", sector: "Communication Services", sub: "Wireless Telecommunication Services" },
  { symbol: "ECL", name: "Ecolab", sector: "Materials", sub: "Specialty Chemicals" },
  { symbol: "ED", name: "Consolidated Edison", sector: "Utilities", sub: "Multi-Utilities" },
  { symbol: "EFX", name: "Equifax", sector: "Industrials", sub: "Research & Consulting Services" },
  { symbol: "EG", name: "Everest Group", sector: "Financials", sub: "Reinsurance" },
  { symbol: "EIX", name: "Edison International", sector: "Utilities", sub: "Electric Utilities" },
  { symbol: "EL", name: "Estée Lauder Companies (The)", sector: "Consumer Staples", sub: "Personal Care Products" },
  { symbol: "ELV", name: "Elevance Health", sector: "Health Care", sub: "Managed Health Care" },
  { symbol: "EME", name: "Emcor", sector: "Industrials", sub: "Construction & Engineering" },
  { symbol: "EMR", name: "Emerson Electric", sector: "Industrials", sub: "Electrical Components & Equipment" },
  { symbol: "EOG", name: "EOG Resources", sector: "Energy", sub: "Oil & Gas Exploration & Production" },
  { symbol: "EQIX", name: "Equinix", sector: "Real Estate", sub: "Data Center REITs" },
  { symbol: "EQR", name: "Equity Residential", sector: "Real Estate", sub: "Multi-Family Residential REITs" },
  { symbol: "EQT", name: "EQT Corporation", sector: "Energy", sub: "Oil & Gas Exploration & Production" },
  { symbol: "ERIE", name: "Erie Indemnity", sector: "Financials", sub: "Insurance Brokers" },
  { symbol: "ES", name: "Eversource Energy", sector: "Utilities", sub: "Electric Utilities" },
  { symbol: "ESS", name: "Essex Property Trust", sector: "Real Estate", sub: "Multi-Family Residential REITs" },
  { symbol: "ETN", name: "Eaton Corporation", sector: "Industrials", sub: "Electrical Components & Equipment" },
  { symbol: "ETR", name: "Entergy", sector: "Utilities", sub: "Electric Utilities" },
  { symbol: "EVRG", name: "Evergy", sector: "Utilities", sub: "Electric Utilities" },
  { symbol: "EW", name: "Edwards Lifesciences", sector: "Health Care", sub: "Health Care Equipment" },
  { symbol: "EXC", name: "Exelon", sector: "Utilities", sub: "Electric Utilities" },
  { symbol: "EXE", name: "Expand Energy", sector: "Energy", sub: "Oil & Gas Exploration & Production" },
  { symbol: "EXPD", name: "Expeditors International", sector: "Industrials", sub: "Air Freight & Logistics" },
  { symbol: "EXPE", name: "Expedia Group", sector: "Consumer Discretionary", sub: "Hotels, Resorts & Cruise Lines" },
  { symbol: "EXR", name: "Extra Space Storage", sector: "Real Estate", sub: "Self-Storage REITs" },
  { symbol: "F", name: "Ford Motor Company", sector: "Consumer Discretionary", sub: "Automobile Manufacturers" },
  { symbol: "FANG", name: "Diamondback Energy", sector: "Energy", sub: "Oil & Gas Exploration & Production" },
  { symbol: "FAST", name: "Fastenal", sector: "Industrials", sub: "Trading Companies & Distributors" },
  { symbol: "FCX", name: "Freeport-McMoRan", sector: "Materials", sub: "Copper" },
  { symbol: "FDS", name: "FactSet", sector: "Financials", sub: "Financial Exchanges & Data" },
  { symbol: "FDX", name: "FedEx", sector: "Industrials", sub: "Air Freight & Logistics" },
  { symbol: "FDXF", name: "FedEx Freight", sector: "Industrials", sub: "Cargo Ground Transportation" },
  { symbol: "FE", name: "FirstEnergy", sector: "Utilities", sub: "Electric Utilities" },
  { symbol: "FFIV", name: "F5, Inc.", sector: "Information Technology", sub: "Communications Equipment" },
  { symbol: "FICO", name: "Fair Isaac", sector: "Information Technology", sub: "Application Software" },
  { symbol: "FIS", name: "Fidelity National Information Services", sector: "Financials", sub: "Transaction & Payment Processing Services" },
  { symbol: "FISV", name: "Fiserv", sector: "Financials", sub: "Transaction & Payment Processing Services" },
  { symbol: "FITB", name: "Fifth Third Bancorp", sector: "Financials", sub: "Regional Banks" },
  { symbol: "FIX", name: "Comfort Systems USA", sector: "Industrials", sub: "Construction & Engineering" },
  { symbol: "FLEX", name: "Flex Ltd.", sector: "Information Technology", sub: "Electronic Manufacturing Services" },
  { symbol: "FOX", name: "Fox Corporation", sector: "Communication Services", sub: "Broadcasting" },
  { symbol: "FOXA", name: "Fox Corporation", sector: "Communication Services", sub: "Broadcasting" },
  { symbol: "FRT", name: "Federal Realty Investment Trust", sector: "Real Estate", sub: "Retail REITs" },
  { symbol: "FSLR", name: "First Solar", sector: "Information Technology", sub: "Semiconductors" },
  { symbol: "FTNT", name: "Fortinet", sector: "Information Technology", sub: "Systems Software" },
  { symbol: "FTV", name: "Fortive", sector: "Industrials", sub: "Industrial Machinery & Supplies & Components" },
  { symbol: "GD", name: "General Dynamics", sector: "Industrials", sub: "Aerospace & Defense" },
  { symbol: "GDDY", name: "GoDaddy", sector: "Information Technology", sub: "Internet Services & Infrastructure" },
  { symbol: "GE", name: "GE Aerospace", sector: "Industrials", sub: "Aerospace & Defense" },
  { symbol: "GEHC", name: "GE HealthCare", sector: "Health Care", sub: "Health Care Equipment" },
  { symbol: "GEN", name: "Gen Digital", sector: "Information Technology", sub: "Systems Software" },
  { symbol: "GEV", name: "GE Vernova", sector: "Industrials", sub: "Heavy Electrical Equipment" },
  { symbol: "GILD", name: "Gilead Sciences", sector: "Health Care", sub: "Biotechnology" },
  { symbol: "GIS", name: "General Mills", sector: "Consumer Staples", sub: "Packaged Foods & Meats" },
  { symbol: "GL", name: "Globe Life", sector: "Financials", sub: "Life & Health Insurance" },
  { symbol: "GLW", name: "Corning Inc.", sector: "Information Technology", sub: "Electronic Components" },
  { symbol: "GM", name: "General Motors", sector: "Consumer Discretionary", sub: "Automobile Manufacturers" },
  { symbol: "GNRC", name: "Generac", sector: "Industrials", sub: "Heavy Electrical Equipment" },
  { symbol: "GOOG", name: "Alphabet Inc.", sector: "Communication Services", sub: "Interactive Media & Services" },
  { symbol: "GOOGL", name: "Alphabet Inc.", sector: "Communication Services", sub: "Interactive Media & Services" },
  { symbol: "GPC", name: "Genuine Parts Company", sector: "Consumer Discretionary", sub: "Distributors" },
  { symbol: "GPN", name: "Global Payments", sector: "Financials", sub: "Transaction & Payment Processing Services" },
  { symbol: "GRMN", name: "Garmin", sector: "Consumer Discretionary", sub: "Consumer Electronics" },
  { symbol: "GS", name: "Goldman Sachs", sector: "Financials", sub: "Investment Banking & Brokerage" },
  { symbol: "GWW", name: "W. W. Grainger", sector: "Industrials", sub: "Industrial Machinery & Supplies & Components" },
  { symbol: "HAL", name: "Halliburton", sector: "Energy", sub: "Oil & Gas Equipment & Services" },
  { symbol: "HAS", name: "Hasbro", sector: "Consumer Discretionary", sub: "Leisure Products" },
  { symbol: "HBAN", name: "Huntington Bancshares", sector: "Financials", sub: "Regional Banks" },
  { symbol: "HCA", name: "HCA Healthcare", sector: "Health Care", sub: "Health Care Facilities" },
  { symbol: "HD", name: "Home Depot (The)", sector: "Consumer Discretionary", sub: "Home Improvement Retail" },
  { symbol: "HIG", name: "Hartford (The)", sector: "Financials", sub: "Property & Casualty Insurance" },
  { symbol: "HII", name: "Huntington Ingalls Industries", sector: "Industrials", sub: "Aerospace & Defense" },
  { symbol: "HLT", name: "Hilton Worldwide", sector: "Consumer Discretionary", sub: "Hotels, Resorts & Cruise Lines" },
  { symbol: "HON", name: "Honeywell Technologies", sector: "Industrials", sub: "Industrial Conglomerates" },
  { symbol: "HONA", name: "Honeywell Aerospace", sector: "Industrials", sub: "Aerospace & Defense" },
  { symbol: "HOOD", name: "Robinhood Markets", sector: "Financials", sub: "Investment Banking & Brokerage" },
  { symbol: "HPE", name: "Hewlett Packard Enterprise", sector: "Information Technology", sub: "Technology Hardware, Storage & Peripherals" },
  { symbol: "HPQ", name: "HP Inc.", sector: "Information Technology", sub: "Technology Hardware, Storage & Peripherals" },
  { symbol: "HRL", name: "Hormel Foods", sector: "Consumer Staples", sub: "Packaged Foods & Meats" },
  { symbol: "HSIC", name: "Henry Schein", sector: "Health Care", sub: "Health Care Distributors" },
  { symbol: "HST", name: "Host Hotels & Resorts", sector: "Real Estate", sub: "Hotel & Resort REITs" },
  { symbol: "HSY", name: "Hershey Company (The)", sector: "Consumer Staples", sub: "Packaged Foods & Meats" },
  { symbol: "HUBB", name: "Hubbell Incorporated", sector: "Industrials", sub: "Industrial Machinery & Supplies & Components" },
  { symbol: "HUM", name: "Humana", sector: "Health Care", sub: "Managed Health Care" },
  { symbol: "HWM", name: "Howmet Aerospace", sector: "Industrials", sub: "Aerospace & Defense" },
  { symbol: "IBKR", name: "Interactive Brokers", sector: "Financials", sub: "Investment Banking & Brokerage" },
  { symbol: "IBM", name: "IBM", sector: "Information Technology", sub: "IT Consulting & Other Services" },
  { symbol: "ICE", name: "Intercontinental Exchange", sector: "Financials", sub: "Financial Exchanges & Data" },
  { symbol: "IDXX", name: "Idexx Laboratories", sector: "Health Care", sub: "Health Care Equipment" },
  { symbol: "IEX", name: "IDEX Corporation", sector: "Industrials", sub: "Industrial Machinery & Supplies & Components" },
  { symbol: "IFF", name: "International Flavors & Fragrances", sector: "Materials", sub: "Specialty Chemicals" },
  { symbol: "INCY", name: "Incyte", sector: "Health Care", sub: "Biotechnology" },
  { symbol: "INTC", name: "Intel", sector: "Information Technology", sub: "Semiconductors" },
  { symbol: "INTU", name: "Intuit", sector: "Information Technology", sub: "Application Software" },
  { symbol: "INVH", name: "Invitation Homes", sector: "Real Estate", sub: "Single-Family Residential REITs" },
  { symbol: "IP", name: "International Paper", sector: "Materials", sub: "Paper & Plastic Packaging Products & Materials" },
  { symbol: "IQV", name: "IQVIA", sector: "Health Care", sub: "Life Sciences Tools & Services" },
  { symbol: "IR", name: "Ingersoll Rand", sector: "Industrials", sub: "Industrial Machinery & Supplies & Components" },
  { symbol: "IRM", name: "Iron Mountain", sector: "Real Estate", sub: "Other Specialized REITs" },
  { symbol: "ISRG", name: "Intuitive Surgical", sector: "Health Care", sub: "Health Care Equipment" },
  { symbol: "IT", name: "Gartner", sector: "Information Technology", sub: "IT Consulting & Other Services" },
  { symbol: "ITW", name: "Illinois Tool Works", sector: "Industrials", sub: "Industrial Machinery & Supplies & Components" },
  { symbol: "IVZ", name: "Invesco", sector: "Financials", sub: "Asset Management & Custody Banks" },
  { symbol: "J", name: "Jacobs Solutions", sector: "Industrials", sub: "Construction & Engineering" },
  { symbol: "JBHT", name: "J.B. Hunt", sector: "Industrials", sub: "Cargo Ground Transportation" },
  { symbol: "JBL", name: "Jabil", sector: "Information Technology", sub: "Electronic Manufacturing Services" },
  { symbol: "JCI", name: "Johnson Controls", sector: "Industrials", sub: "Building Products" },
  { symbol: "JKHY", name: "Jack Henry & Associates", sector: "Financials", sub: "Transaction & Payment Processing Services" },
  { symbol: "JNJ", name: "Johnson & Johnson", sector: "Health Care", sub: "Pharmaceuticals" },
  { symbol: "JPM", name: "JPMorgan Chase", sector: "Financials", sub: "Diversified Banks" },
  { symbol: "KDP", name: "Keurig Dr Pepper", sector: "Consumer Staples", sub: "Soft Drinks & Non-alcoholic Beverages" },
  { symbol: "KEY", name: "KeyCorp", sector: "Financials", sub: "Regional Banks" },
  { symbol: "KEYS", name: "Keysight Technologies", sector: "Information Technology", sub: "Electronic Equipment & Instruments" },
  { symbol: "KHC", name: "Kraft Heinz", sector: "Consumer Staples", sub: "Packaged Foods & Meats" },
  { symbol: "KIM", name: "Kimco Realty", sector: "Real Estate", sub: "Retail REITs" },
  { symbol: "KKR", name: "KKR & Co.", sector: "Financials", sub: "Asset Management & Custody Banks" },
  { symbol: "KLAC", name: "KLA Corporation", sector: "Information Technology", sub: "Semiconductor Materials & Equipment" },
  { symbol: "KMB", name: "Kimberly-Clark", sector: "Consumer Staples", sub: "Household Products" },
  { symbol: "KMI", name: "Kinder Morgan", sector: "Energy", sub: "Oil & Gas Storage & Transportation" },
  { symbol: "KO", name: "Coca-Cola Company (The)", sector: "Consumer Staples", sub: "Soft Drinks & Non-alcoholic Beverages" },
  { symbol: "KR", name: "Kroger", sector: "Consumer Staples", sub: "Food Retail" },
  { symbol: "KVUE", name: "Kenvue", sector: "Consumer Staples", sub: "Personal Care Products" },
  { symbol: "L", name: "Loews Corporation", sector: "Financials", sub: "Multi-line Insurance" },
  { symbol: "LDOS", name: "Leidos", sector: "Industrials", sub: "Diversified Support Services" },
  { symbol: "LEN", name: "Lennar", sector: "Consumer Discretionary", sub: "Homebuilding" },
  { symbol: "LH", name: "Labcorp", sector: "Health Care", sub: "Health Care Services" },
  { symbol: "LHX", name: "L3Harris", sector: "Industrials", sub: "Aerospace & Defense" },
  { symbol: "LII", name: "Lennox International", sector: "Industrials", sub: "Building Products" },
  { symbol: "LIN", name: "Linde plc", sector: "Materials", sub: "Industrial Gases" },
  { symbol: "LITE", name: "Lumentum", sector: "Information Technology", sub: "Communications Equipment" },
  { symbol: "LLY", name: "Lilly (Eli)", sector: "Health Care", sub: "Pharmaceuticals" },
  { symbol: "LMT", name: "Lockheed Martin", sector: "Industrials", sub: "Aerospace & Defense" },
  { symbol: "LNT", name: "Alliant Energy", sector: "Utilities", sub: "Electric Utilities" },
  { symbol: "LOW", name: "Lowe's", sector: "Consumer Discretionary", sub: "Home Improvement Retail" },
  { symbol: "LRCX", name: "Lam Research", sector: "Information Technology", sub: "Semiconductor Materials & Equipment" },
  { symbol: "LULU", name: "Lululemon Athletica", sector: "Consumer Discretionary", sub: "Apparel, Accessories & Luxury Goods" },
  { symbol: "LUV", name: "Southwest Airlines", sector: "Industrials", sub: "Passenger Airlines" },
  { symbol: "LVS", name: "Las Vegas Sands", sector: "Consumer Discretionary", sub: "Casinos & Gaming" },
  { symbol: "LYB", name: "LyondellBasell", sector: "Materials", sub: "Specialty Chemicals" },
  { symbol: "LYV", name: "Live Nation Entertainment", sector: "Communication Services", sub: "Movies & Entertainment" },
  { symbol: "MA", name: "Mastercard", sector: "Financials", sub: "Transaction & Payment Processing Services" },
  { symbol: "MAA", name: "Mid-America Apartment Communities", sector: "Real Estate", sub: "Multi-Family Residential REITs" },
  { symbol: "MAR", name: "Marriott International", sector: "Consumer Discretionary", sub: "Hotels, Resorts & Cruise Lines" },
  { symbol: "MAS", name: "Masco", sector: "Industrials", sub: "Building Products" },
  { symbol: "MCD", name: "McDonald's", sector: "Consumer Discretionary", sub: "Restaurants" },
  { symbol: "MCHP", name: "Microchip Technology", sector: "Information Technology", sub: "Semiconductors" },
  { symbol: "MCK", name: "McKesson Corporation", sector: "Health Care", sub: "Health Care Distributors" },
  { symbol: "MCO", name: "Moody's Corporation", sector: "Financials", sub: "Financial Exchanges & Data" },
  { symbol: "MDLZ", name: "Mondelez International", sector: "Consumer Staples", sub: "Packaged Foods & Meats" },
  { symbol: "MDT", name: "Medtronic", sector: "Health Care", sub: "Health Care Equipment" },
  { symbol: "MET", name: "MetLife", sector: "Financials", sub: "Life & Health Insurance" },
  { symbol: "META", name: "Meta Platforms", sector: "Communication Services", sub: "Interactive Media & Services" },
  { symbol: "MGM", name: "MGM Resorts", sector: "Consumer Discretionary", sub: "Casinos & Gaming" },
  { symbol: "MKC", name: "McCormick & Company", sector: "Consumer Staples", sub: "Packaged Foods & Meats" },
  { symbol: "MLM", name: "Martin Marietta Materials", sector: "Materials", sub: "Construction Materials" },
  { symbol: "MMM", name: "3M", sector: "Industrials", sub: "Industrial Conglomerates" },
  { symbol: "MNST", name: "Monster Beverage", sector: "Consumer Staples", sub: "Soft Drinks & Non-alcoholic Beverages" },
  { symbol: "MO", name: "Altria", sector: "Consumer Staples", sub: "Tobacco" },
  { symbol: "MOS", name: "Mosaic Company (The)", sector: "Materials", sub: "Fertilizers & Agricultural Chemicals" },
  { symbol: "MPC", name: "Marathon Petroleum", sector: "Energy", sub: "Oil & Gas Refining & Marketing" },
  { symbol: "MPWR", name: "Monolithic Power Systems", sector: "Information Technology", sub: "Semiconductors" },
  { symbol: "MRK", name: "Merck & Co.", sector: "Health Care", sub: "Pharmaceuticals" },
  { symbol: "MRNA", name: "Moderna", sector: "Health Care", sub: "Biotechnology" },
  { symbol: "MRSH", name: "Marsh McLennan", sector: "Financials", sub: "Insurance Brokers" },
  { symbol: "MRVL", name: "Marvell Technology", sector: "Information Technology", sub: "Semiconductors" },
  { symbol: "MS", name: "Morgan Stanley", sector: "Financials", sub: "Investment Banking & Brokerage" },
  { symbol: "MSCI", name: "MSCI Inc.", sector: "Financials", sub: "Financial Exchanges & Data" },
  { symbol: "MSFT", name: "Microsoft", sector: "Information Technology", sub: "Systems Software" },
  { symbol: "MSI", name: "Motorola Solutions", sector: "Information Technology", sub: "Communications Equipment" },
  { symbol: "MTB", name: "M&T Bank", sector: "Financials", sub: "Regional Banks" },
  { symbol: "MTD", name: "Mettler Toledo", sector: "Health Care", sub: "Life Sciences Tools & Services" },
  { symbol: "MU", name: "Micron Technology", sector: "Information Technology", sub: "Semiconductors" },
  { symbol: "NCLH", name: "Norwegian Cruise Line Holdings", sector: "Consumer Discretionary", sub: "Hotels, Resorts & Cruise Lines" },
  { symbol: "NDAQ", name: "Nasdaq, Inc.", sector: "Financials", sub: "Financial Exchanges & Data" },
  { symbol: "NDSN", name: "Nordson Corporation", sector: "Industrials", sub: "Industrial Machinery & Supplies & Components" },
  { symbol: "NEE", name: "NextEra Energy", sector: "Utilities", sub: "Multi-Utilities" },
  { symbol: "NEM", name: "Newmont", sector: "Materials", sub: "Gold" },
  { symbol: "NFLX", name: "Netflix", sector: "Communication Services", sub: "Movies & Entertainment" },
  { symbol: "NI", name: "NiSource", sector: "Utilities", sub: "Multi-Utilities" },
  { symbol: "NKE", name: "Nike, Inc.", sector: "Consumer Discretionary", sub: "Apparel, Accessories & Luxury Goods" },
  { symbol: "NOC", name: "Northrop Grumman", sector: "Industrials", sub: "Aerospace & Defense" },
  { symbol: "NOW", name: "ServiceNow", sector: "Information Technology", sub: "Systems Software" },
  { symbol: "NRG", name: "NRG Energy", sector: "Utilities", sub: "Independent Power Producers & Energy Traders" },
  { symbol: "NSC", name: "Norfolk Southern", sector: "Industrials", sub: "Rail Transportation" },
  { symbol: "NTAP", name: "NetApp", sector: "Information Technology", sub: "Technology Hardware, Storage & Peripherals" },
  { symbol: "NTRS", name: "Northern Trust", sector: "Financials", sub: "Asset Management & Custody Banks" },
  { symbol: "NUE", name: "Nucor", sector: "Materials", sub: "Steel" },
  { symbol: "NVDA", name: "Nvidia", sector: "Information Technology", sub: "Semiconductors" },
  { symbol: "NVR", name: "NVR, Inc.", sector: "Consumer Discretionary", sub: "Homebuilding" },
  { symbol: "NWS", name: "News Corp", sector: "Communication Services", sub: "Publishing" },
  { symbol: "NWSA", name: "News Corp", sector: "Communication Services", sub: "Publishing" },
  { symbol: "NXPI", name: "NXP Semiconductors", sector: "Information Technology", sub: "Semiconductors" },
  { symbol: "O", name: "Realty Income", sector: "Real Estate", sub: "Retail REITs" },
  { symbol: "ODFL", name: "Old Dominion", sector: "Industrials", sub: "Cargo Ground Transportation" },
  { symbol: "OKE", name: "Oneok", sector: "Energy", sub: "Oil & Gas Storage & Transportation" },
  { symbol: "OMC", name: "Omnicom Group", sector: "Communication Services", sub: "Advertising" },
  { symbol: "ON", name: "ON Semiconductor", sector: "Information Technology", sub: "Semiconductors" },
  { symbol: "ORCL", name: "Oracle Corporation", sector: "Information Technology", sub: "Application Software" },
  { symbol: "ORLY", name: "O’Reilly Automotive", sector: "Consumer Discretionary", sub: "Automotive Retail" },
  { symbol: "OTIS", name: "Otis Worldwide", sector: "Industrials", sub: "Industrial Machinery & Supplies & Components" },
  { symbol: "OXY", name: "Occidental Petroleum", sector: "Energy", sub: "Oil & Gas Exploration & Production" },
  { symbol: "PANW", name: "Palo Alto Networks", sector: "Information Technology", sub: "Systems Software" },
  { symbol: "PAYX", name: "Paychex", sector: "Industrials", sub: "Human Resource & Employment Services" },
  { symbol: "PCAR", name: "Paccar", sector: "Industrials", sub: "Construction Machinery & Heavy Transportation Equipment" },
  { symbol: "PCG", name: "PG&E Corporation", sector: "Utilities", sub: "Multi-Utilities" },
  { symbol: "PEG", name: "Public Service Enterprise Group", sector: "Utilities", sub: "Electric Utilities" },
  { symbol: "PEP", name: "PepsiCo", sector: "Consumer Staples", sub: "Soft Drinks & Non-alcoholic Beverages" },
  { symbol: "PFE", name: "Pfizer", sector: "Health Care", sub: "Pharmaceuticals" },
  { symbol: "PFG", name: "Principal Financial Group", sector: "Financials", sub: "Life & Health Insurance" },
  { symbol: "PG", name: "Procter & Gamble", sector: "Consumer Staples", sub: "Personal Care Products" },
  { symbol: "PGR", name: "Progressive Corporation", sector: "Financials", sub: "Property & Casualty Insurance" },
  { symbol: "PH", name: "Parker Hannifin", sector: "Industrials", sub: "Industrial Machinery & Supplies & Components" },
  { symbol: "PHM", name: "PulteGroup", sector: "Consumer Discretionary", sub: "Homebuilding" },
  { symbol: "PKG", name: "Packaging Corporation of America", sector: "Materials", sub: "Paper & Plastic Packaging Products & Materials" },
  { symbol: "PLD", name: "Prologis", sector: "Real Estate", sub: "Industrial REITs" },
  { symbol: "PLTR", name: "Palantir Technologies", sector: "Information Technology", sub: "Application Software" },
  { symbol: "PM", name: "Philip Morris International", sector: "Consumer Staples", sub: "Tobacco" },
  { symbol: "PNC", name: "PNC Financial Services", sector: "Financials", sub: "Diversified Banks" },
  { symbol: "PNR", name: "Pentair", sector: "Industrials", sub: "Industrial Machinery & Supplies & Components" },
  { symbol: "PNW", name: "Pinnacle West Capital", sector: "Utilities", sub: "Multi-Utilities" },
  { symbol: "PPG", name: "PPG Industries", sector: "Materials", sub: "Specialty Chemicals" },
  { symbol: "PPL", name: "PPL Corporation", sector: "Utilities", sub: "Electric Utilities" },
  { symbol: "PRU", name: "Prudential Financial", sector: "Financials", sub: "Life & Health Insurance" },
  { symbol: "PSA", name: "Public Storage", sector: "Real Estate", sub: "Self-Storage REITs" },
  { symbol: "PSKY", name: "Paramount Skydance Corporation", sector: "Communication Services", sub: "Movies & Entertainment" },
  { symbol: "PSX", name: "Phillips 66", sector: "Energy", sub: "Oil & Gas Refining & Marketing" },
  { symbol: "PTC", name: "PTC Inc.", sector: "Information Technology", sub: "Application Software" },
  { symbol: "PWR", name: "Quanta Services", sector: "Industrials", sub: "Construction & Engineering" },
  { symbol: "PYPL", name: "PayPal", sector: "Financials", sub: "Transaction & Payment Processing Services" },
  { symbol: "Q", name: "Qnity Electronics", sector: "Information Technology", sub: "Semiconductor Materials & Equipment" },
  { symbol: "QCOM", name: "Qualcomm", sector: "Information Technology", sub: "Semiconductors" },
  { symbol: "RCL", name: "Royal Caribbean Group", sector: "Consumer Discretionary", sub: "Hotels, Resorts & Cruise Lines" },
  { symbol: "REG", name: "Regency Centers", sector: "Real Estate", sub: "Retail REITs" },
  { symbol: "REGN", name: "Regeneron Pharmaceuticals", sector: "Health Care", sub: "Biotechnology" },
  { symbol: "RF", name: "Regions Financial Corporation", sector: "Financials", sub: "Regional Banks" },
  { symbol: "RJF", name: "Raymond James Financial", sector: "Financials", sub: "Investment Banking & Brokerage" },
  { symbol: "RL", name: "Ralph Lauren Corporation", sector: "Consumer Discretionary", sub: "Apparel, Accessories & Luxury Goods" },
  { symbol: "RMD", name: "ResMed", sector: "Health Care", sub: "Health Care Equipment" },
  { symbol: "ROK", name: "Rockwell Automation", sector: "Industrials", sub: "Electrical Components & Equipment" },
  { symbol: "ROL", name: "Rollins, Inc.", sector: "Industrials", sub: "Environmental & Facilities Services" },
  { symbol: "ROP", name: "Roper Technologies", sector: "Information Technology", sub: "Electronic Equipment & Instruments" },
  { symbol: "ROST", name: "Ross Stores", sector: "Consumer Discretionary", sub: "Apparel Retail" },
  { symbol: "RSG", name: "Republic Services", sector: "Industrials", sub: "Environmental & Facilities Services" },
  { symbol: "RTX", name: "RTX Corporation", sector: "Industrials", sub: "Aerospace & Defense" },
  { symbol: "RVTY", name: "Revvity", sector: "Health Care", sub: "Health Care Equipment" },
  { symbol: "SBAC", name: "SBA Communications", sector: "Real Estate", sub: "Telecom Tower REITs" },
  { symbol: "SBUX", name: "Starbucks", sector: "Consumer Discretionary", sub: "Restaurants" },
  { symbol: "SCHW", name: "Charles Schwab Corporation", sector: "Financials", sub: "Investment Banking & Brokerage" },
  { symbol: "SHW", name: "Sherwin-Williams", sector: "Materials", sub: "Specialty Chemicals" },
  { symbol: "SJM", name: "J.M. Smucker Company (The)", sector: "Consumer Staples", sub: "Packaged Foods & Meats" },
  { symbol: "SLB", name: "Schlumberger", sector: "Energy", sub: "Oil & Gas Equipment & Services" },
  { symbol: "SMCI", name: "Supermicro", sector: "Information Technology", sub: "Technology Hardware, Storage & Peripherals" },
  { symbol: "SNA", name: "Snap-on", sector: "Industrials", sub: "Industrial Machinery & Supplies & Components" },
  { symbol: "SNDK", name: "Sandisk", sector: "Information Technology", sub: "Technology Hardware, Storage & Peripherals" },
  { symbol: "SNPS", name: "Synopsys", sector: "Information Technology", sub: "Application Software" },
  { symbol: "SO", name: "Southern Company", sector: "Utilities", sub: "Electric Utilities" },
  { symbol: "SOLV", name: "Solventum", sector: "Health Care", sub: "Health Care Technology" },
  { symbol: "SPG", name: "Simon Property Group", sector: "Real Estate", sub: "Retail REITs" },
  { symbol: "SPGI", name: "S&P Global", sector: "Financials", sub: "Financial Exchanges & Data" },
  { symbol: "SRE", name: "Sempra", sector: "Utilities", sub: "Multi-Utilities" },
  { symbol: "STE", name: "Steris", sector: "Health Care", sub: "Health Care Equipment" },
  { symbol: "STLD", name: "Steel Dynamics", sector: "Materials", sub: "Steel" },
  { symbol: "STT", name: "State Street Corporation", sector: "Financials", sub: "Asset Management & Custody Banks" },
  { symbol: "STX", name: "Seagate Technology", sector: "Information Technology", sub: "Technology Hardware, Storage & Peripherals" },
  { symbol: "STZ", name: "Constellation Brands", sector: "Consumer Staples", sub: "Distillers & Vintners" },
  { symbol: "SW", name: "Smurfit Westrock", sector: "Materials", sub: "Paper & Plastic Packaging Products & Materials" },
  { symbol: "SWK", name: "Stanley Black & Decker", sector: "Industrials", sub: "Industrial Machinery & Supplies & Components" },
  { symbol: "SWKS", name: "Skyworks Solutions", sector: "Information Technology", sub: "Semiconductors" },
  { symbol: "SYF", name: "Synchrony Financial", sector: "Financials", sub: "Consumer Finance" },
  { symbol: "SYK", name: "Stryker Corporation", sector: "Health Care", sub: "Health Care Equipment" },
  { symbol: "SYY", name: "Sysco", sector: "Consumer Staples", sub: "Food Distributors" },
  { symbol: "T", name: "AT&T", sector: "Communication Services", sub: "Integrated Telecommunication Services" },
  { symbol: "TAP", name: "Molson Coors Beverage Company", sector: "Consumer Staples", sub: "Brewers" },
  { symbol: "TDG", name: "TransDigm Group", sector: "Industrials", sub: "Aerospace & Defense" },
  { symbol: "TDY", name: "Teledyne Technologies", sector: "Information Technology", sub: "Electronic Equipment & Instruments" },
  { symbol: "TECH", name: "Bio-Techne", sector: "Health Care", sub: "Life Sciences Tools & Services" },
  { symbol: "TEL", name: "TE Connectivity", sector: "Information Technology", sub: "Electronic Manufacturing Services" },
  { symbol: "TER", name: "Teradyne", sector: "Information Technology", sub: "Semiconductor Materials & Equipment" },
  { symbol: "TFC", name: "Truist Financial", sector: "Financials", sub: "Diversified Banks" },
  { symbol: "TGT", name: "Target Corporation", sector: "Consumer Staples", sub: "Consumer Staples Merchandise Retail" },
  { symbol: "TJX", name: "TJX Companies", sector: "Consumer Discretionary", sub: "Apparel Retail" },
  { symbol: "TKO", name: "TKO Group Holdings", sector: "Communication Services", sub: "Movies & Entertainment" },
  { symbol: "TMO", name: "Thermo Fisher Scientific", sector: "Health Care", sub: "Life Sciences Tools & Services" },
  { symbol: "TMUS", name: "T-Mobile US", sector: "Communication Services", sub: "Wireless Telecommunication Services" },
  { symbol: "TPL", name: "Texas Pacific Land Corporation", sector: "Energy", sub: "Oil & Gas Exploration & Production" },
  { symbol: "TPR", name: "Tapestry, Inc.", sector: "Consumer Discretionary", sub: "Apparel, Accessories & Luxury Goods" },
  { symbol: "TRGP", name: "Targa Resources", sector: "Energy", sub: "Oil & Gas Storage & Transportation" },
  { symbol: "TRMB", name: "Trimble Inc.", sector: "Information Technology", sub: "Application Software" },
  { symbol: "TROW", name: "T. Rowe Price", sector: "Financials", sub: "Asset Management & Custody Banks" },
  { symbol: "TRV", name: "Travelers Companies (The)", sector: "Financials", sub: "Property & Casualty Insurance" },
  { symbol: "TSCO", name: "Tractor Supply", sector: "Consumer Discretionary", sub: "Other Specialty Retail" },
  { symbol: "TSLA", name: "Tesla, Inc.", sector: "Consumer Discretionary", sub: "Automobile Manufacturers" },
  { symbol: "TSN", name: "Tyson Foods", sector: "Consumer Staples", sub: "Packaged Foods & Meats" },
  { symbol: "TT", name: "Trane Technologies", sector: "Industrials", sub: "Building Products" },
  { symbol: "TTD", name: "Trade Desk (The)", sector: "Communication Services", sub: "Advertising" },
  { symbol: "TTWO", name: "Take-Two Interactive", sector: "Communication Services", sub: "Interactive Home Entertainment" },
  { symbol: "TXN", name: "Texas Instruments", sector: "Information Technology", sub: "Semiconductors" },
  { symbol: "TXT", name: "Textron", sector: "Industrials", sub: "Aerospace & Defense" },
  { symbol: "TYL", name: "Tyler Technologies", sector: "Information Technology", sub: "Application Software" },
  { symbol: "UAL", name: "United Airlines Holdings", sector: "Industrials", sub: "Passenger Airlines" },
  { symbol: "UBER", name: "Uber", sector: "Industrials", sub: "Passenger Ground Transportation" },
  { symbol: "UDR", name: "UDR, Inc.", sector: "Real Estate", sub: "Multi-Family Residential REITs" },
  { symbol: "UHS", name: "Universal Health Services", sector: "Health Care", sub: "Health Care Facilities" },
  { symbol: "ULTA", name: "Ulta Beauty", sector: "Consumer Discretionary", sub: "Other Specialty Retail" },
  { symbol: "UNH", name: "UnitedHealth Group", sector: "Health Care", sub: "Managed Health Care" },
  { symbol: "UNP", name: "Union Pacific Corporation", sector: "Industrials", sub: "Rail Transportation" },
  { symbol: "UPS", name: "United Parcel Service", sector: "Industrials", sub: "Air Freight & Logistics" },
  { symbol: "URI", name: "United Rentals", sector: "Industrials", sub: "Trading Companies & Distributors" },
  { symbol: "USB", name: "U.S. Bancorp", sector: "Financials", sub: "Diversified Banks" },
  { symbol: "V", name: "Visa Inc.", sector: "Financials", sub: "Transaction & Payment Processing Services" },
  { symbol: "VEEV", name: "Veeva Systems", sector: "Health Care", sub: "Health Care Technology" },
  { symbol: "VICI", name: "Vici Properties", sector: "Real Estate", sub: "Hotel & Resort REITs" },
  { symbol: "VLO", name: "Valero Energy", sector: "Energy", sub: "Oil & Gas Refining & Marketing" },
  { symbol: "VLTO", name: "Veralto", sector: "Industrials", sub: "Environmental & Facilities Services" },
  { symbol: "VMC", name: "Vulcan Materials Company", sector: "Materials", sub: "Construction Materials" },
  { symbol: "VRSK", name: "Verisk Analytics", sector: "Industrials", sub: "Research & Consulting Services" },
  { symbol: "VRSN", name: "Verisign", sector: "Information Technology", sub: "Internet Services & Infrastructure" },
  { symbol: "VRT", name: "Vertiv", sector: "Industrials", sub: "Electrical Components & Equipment" },
  { symbol: "VRTX", name: "Vertex Pharmaceuticals", sector: "Health Care", sub: "Biotechnology" },
  { symbol: "VST", name: "Vistra Corp", sector: "Utilities", sub: "Electric Utilities" },
  { symbol: "VTR", name: "Ventas", sector: "Real Estate", sub: "Health Care REITs" },
  { symbol: "VTRS", name: "Viatris", sector: "Health Care", sub: "Pharmaceuticals" },
  { symbol: "VZ", name: "Verizon", sector: "Communication Services", sub: "Integrated Telecommunication Services" },
  { symbol: "WAB", name: "Wabtec", sector: "Industrials", sub: "Construction Machinery & Heavy Transportation Equipment" },
  { symbol: "WAT", name: "Waters Corporation", sector: "Health Care", sub: "Life Sciences Tools & Services" },
  { symbol: "WBD", name: "Warner Bros. Discovery", sector: "Communication Services", sub: "Broadcasting" },
  { symbol: "WDAY", name: "Workday, Inc.", sector: "Information Technology", sub: "Application Software" },
  { symbol: "WDC", name: "Western Digital", sector: "Information Technology", sub: "Technology Hardware, Storage & Peripherals" },
  { symbol: "WEC", name: "WEC Energy Group", sector: "Utilities", sub: "Electric Utilities" },
  { symbol: "WELL", name: "Welltower", sector: "Real Estate", sub: "Health Care REITs" },
  { symbol: "WFC", name: "Wells Fargo", sector: "Financials", sub: "Diversified Banks" },
  { symbol: "WM", name: "Waste Management", sector: "Industrials", sub: "Environmental & Facilities Services" },
  { symbol: "WMB", name: "Williams Companies", sector: "Energy", sub: "Oil & Gas Storage & Transportation" },
  { symbol: "WMT", name: "Walmart", sector: "Consumer Staples", sub: "Consumer Staples Merchandise Retail" },
  { symbol: "WRB", name: "W. R. Berkley Corporation", sector: "Financials", sub: "Property & Casualty Insurance" },
  { symbol: "WSM", name: "Williams-Sonoma, Inc.", sector: "Consumer Discretionary", sub: "Homefurnishing Retail" },
  { symbol: "WST", name: "West Pharmaceutical Services", sector: "Health Care", sub: "Health Care Supplies" },
  { symbol: "WTW", name: "Willis Towers Watson", sector: "Financials", sub: "Insurance Brokers" },
  { symbol: "WY", name: "Weyerhaeuser", sector: "Real Estate", sub: "Timber REITs" },
  { symbol: "WYNN", name: "Wynn Resorts", sector: "Consumer Discretionary", sub: "Casinos & Gaming" },
  { symbol: "XEL", name: "Xcel Energy", sector: "Utilities", sub: "Multi-Utilities" },
  { symbol: "XOM", name: "ExxonMobil", sector: "Energy", sub: "Integrated Oil & Gas" },
  { symbol: "XYL", name: "Xylem Inc.", sector: "Industrials", sub: "Industrial Machinery & Supplies & Components" },
  { symbol: "XYZ", name: "Block, Inc.", sector: "Financials", sub: "Transaction & Payment Processing Services" },
  { symbol: "YUM", name: "Yum! Brands", sector: "Consumer Discretionary", sub: "Restaurants" },
  { symbol: "ZBH", name: "Zimmer Biomet", sector: "Health Care", sub: "Health Care Equipment" },
  { symbol: "ZBRA", name: "Zebra Technologies", sector: "Information Technology", sub: "Electronic Equipment & Instruments" },
  { symbol: "ZTS", name: "Zoetis", sector: "Health Care", sub: "Pharmaceuticals" },
];

/** Tüm endekslerin birleşimi — sembol başına tek kayıt. */
export const ALL_MEMBERS: IndexMember[] = (() => {
  const map = new Map<string, IndexMember>();
  for (const member of [...SPX_MEMBERS, ...NDX_MEMBERS, ...DOW_MEMBERS]) {
    const current = map.get(member.symbol);
    // Sektörü olan kayıt tercih edilir.
    if (!current || (!current.sector && member.sector)) map.set(member.symbol, member);
  }
  return [...map.values()];
})();

const BY_SYMBOL = new Map(ALL_MEMBERS.map((m) => [m.symbol, m]));

export function indexMemberOf(symbol: string): IndexMember | null {
  return BY_SYMBOL.get(symbol) ?? null;
}

/** Aynı GICS alt sektöründeki diğer şirketler — hisse detayındaki öneriler. */
export function peersOf(symbol: string): IndexMember[] {
  const member = BY_SYMBOL.get(symbol);
  if (!member?.sub) return [];
  return ALL_MEMBERS.filter(
    (other) => other.symbol !== symbol && other.sub === member.sub,
  );
}
